### ISSUE TITLE
Swagger Authorize With Keycloak Get Message "we are sorry"

### ISSUE THREAD

**Issue by alihdev** [abpframework/eShopOnAbp#145]
oauth2 (OAuth2, authorizationCode)
Authorization URL: http://localhost:8080/realms/master/connect/authorize
Token URL: http://localhost:8080/realms/master/connect/token
Flow: authorizationCode

![image](https://user-images.githubusercontent.com/97635301/208613579-6ed6500e-d7ce-4118-bd52-235657d55e6f.png)

**Comment by malikmasis** [comment]
Hi Ali,
I could reproduce the issue. I've created an issue https://github.com/abpframework/abp/issues/15183
Thanks for your feedback.

**Comment by alihdev** [comment]
Thank you. We look forward to solving this problem.
