### ISSUE TITLE
Paypal credentials issue while running the application with tye

### ISSUE THREAD

**Issue by odidev** [abpframework/eShopOnAbp#166]
I am working with eShopOnAbp on the Ubuntu AWS instance. 

I am following the instructions here: < https://github.com/abpframework/eShopOnAbp#instructions > to run eShopOnAbp. 

As per the instructions, we need to have a Paypal clientID and secret, which will be hardcoded in the .env file before executing `tye run` to run the project. 

And if I try running `tye run` without adding Paypal clientID and secret in the .env file, I get the below error: 
~~~ 
Evaluated project metadata file could not be found for service identity-service 
~~~ 

May I know, is it mandatory to add PayPal credentials in the environment file before running tye, or is there a workaround?

**Comment by gterdem** [comment]
When running on tye, payment service uses this environment variable. It doesn't have to be a valid information, just the key in enough.

Or you can simply remove it from tye.yaml file:

https://github.com/abpframework/eShopOnAbp/blob/f1c51a2a2777d8784868f13fb0d0646a0f52b42f/tye.yaml#L65-L66

**Comment by gterdem** [comment]
You can try deleting `obj` folders.
https://github.com/dotnet/tye/issues/766#issuecomment-730285006

**Comment by odidev** [comment]
The issue is resolved after updating dotnet to version 7 on my x86 AWS instance. 

However, on the **Linux/ARM64 Ubuntu AWS instance**, I successfully installed dotnet 7 following [this](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) document, installed `tye` and then executed `tye run`. I am getting the below error: 
~~~ 
$ tye run

You must install or update .NET to run this application. 

App: /home/ubuntu/.dotnet/tools/tye 
Architecture: arm64 
Framework: 'Microsoft.NETCore.App', version '6.0.0' (arm64) 
.NET location: /home/ubuntu/rahul/.dotnet 

The following frameworks were found: 
  7.0.4 at [/home/ubuntu/rahul/.dotnet/shared/Microsoft.NETCore.App] 

Learn about framework resolution: 
https://aka.ms/dotnet/app-launch-failed 

To install missing framework, download: 

https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=arm64&rid=ubuntu.22.04-arm64 
~~~ 

I already exported DOTNET to PATH, but that hasn’t helped. 

Do you have any suggestions on the same for **Linux/ARM64** platform?

**Comment by gterdem** [comment]
[dotnet/tye](https://github.com/dotnet/tye/blob/main/docs/getting_started.md#installing-tye) still requires .NET6 SDK.

They'll probably update it for .Net7 or .Net8 hopefully soon.
