### ISSUE TITLE
"Error starting gRPC call" when adding to basket

### ISSUE THREAD

**Issue by jeremiahflaga** [abpframework/eShopOnAbp#168]
This might be a dumb question because I have not looked into gRPC very closely yet.

I'm getting this error when I click on "Add to basket" in the public facing app (https://localhost:44335/)

`Grpc.Core.RpcException: 'Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:81) SocketException: No connection could be made because the target machine actively refused it.", DebugException="System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:81)`

Please give some guidance on how I can fix this. I just want to successfully run the app, then explore the code after that.

Thanks.

**Comment by gterdem** [comment]
It seems like the catalog service is not up and running. Check the logs for the Catalog microservice please.

**Comment by jeremiahflaga** [comment]
Hi @gterdem , thanks for responding.

This is the error I have in my log file:

`2023-05-08 03:08:20.453 +08:00 [ERR] Failed executing DbCommand (2ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT a."Id", a."DisplayName", a."ExtraProperties", a."Name"
FROM "AbpPermissionGroups" AS a
2023-05-08 03:08:20.455 +08:00 [ERR] An exception occurred while iterating over the results of a query for context type 'EShopOnAbp.AdministrationService.EntityFrameworkCore.AdministrationServiceDbContext'.
Npgsql.PostgresException (0x80004005): 42P01: relation "AbpPermissionGroups" does not exist`

**Comment by gterdem** [comment]
Closed by https://github.com/abpframework/eShopOnAbp/pull/170

Thank you!
