### ISSUE TITLE
How to solve the error problem of yarp in docker

### ISSUE THREAD

**Issue by sevenNightL** [abpframework/eShopOnAbp#171]
I published the program on the docker, but the gatewey project cannot be opened. How to solve this problem?

<img width="1318" alt="image" src="https://github.com/abpframework/eShopOnAbp/assets/27542146/7360ff9e-6e7c-4464-bf60-bde6da38baa2">

<img width="790" alt="image" src="https://github.com/abpframework/eShopOnAbp/assets/27542146/a6d5fb10-5ada-45e0-a346-a2b804a447ff">

**Comment by gterdem** [comment]
It is a known issue.

See https://github.com/abpframework/abp/issues/15601

We'll try to find a work-around for this problem.
