### ISSUE TITLE
Account management and User management issues

### ISSUE THREAD

**Issue by jflaga** [abpframework/eShopOnAbp#176]
When I click on the My Account menu in the Public Web app

![image](https://github.com/abpframework/eShopOnAbp/assets/108422823/f259c999-64ad-4d2a-9bca-76c9fcc38278)

... it redirects me to `http://localhost:8080/realms/master/Account/Manage`, which displays the error "Page not found".

Also, when I create a user in the Identity management page of the angular app, then login using that user, I am not able to login.

Is there an ongoing fix regarding these issues?

Best regards.

**Comment by gterdem** [comment]
We'll fix the broken manage account link in no time but we need to discuss about the user management.

We've moved to **Keycloak** which already has user management. We need to discuss if we want to keep identity management administration.
1- If we do, It will be a sort of duplicate users in both IdentityService and the Keycloak.
2- If we don't, we'll need to handle permission and role assignments to the Keycloak users.

We'll discuss about it for a best common scenario demonstration.

**Comment by jflaga** [comment]
Thanks @gterdem for the information.

**Comment by jflaga** [comment]
Hi @gterdem , may I know whether you have already decided to keep or not to keep the identity management administration?
