### ISSUE TITLE
Visual Studio 2022 debug issue

### ISSUE THREAD

**Issue by wbx58585888** [abpframework/eShopOnAbp#177]
First I run docker to make  environment .Its ok.
 
Then i config the properties
![image](https://github.com/abpframework/eShopOnAbp/assets/55383628/35647b71-65f4-457e-b791-c80310bdfcef)

Then i hitting the run button to debug 
![image](https://github.com/abpframework/eShopOnAbp/assets/55383628/d064c163-cac7-44ca-9f3d-afb74bb6fb2c)

Most  errors are missing dlls .I check the   dll files . Its exactly missing .I cant  build the dll  ,because the csproj   debug has the same dlls missing errors.
Pls help 
Best regards.

**Comment by maliming** [comment]
Try to build the solution by `dotnet build /graphBuild` first.

**Comment by wbx58585888** [comment]
> Try to build the solution by `dotnet build /graphBuild` first.

Its work.There is new error like  connect  db fail.
![image](https://github.com/abpframework/eShopOnAbp/assets/55383628/ceb6925f-d630-4bc2-9539-b7eb2ba5dfb3)
![image](https://github.com/abpframework/eShopOnAbp/assets/55383628/ba5d83e4-f624-41e5-a13c-a891bdd8c2ac)

My docker is running .
![image](https://github.com/abpframework/eShopOnAbp/assets/55383628/1045825a-ad0a-40f5-95af-4ac21b09e78f)

Pls help
Best regards.

**Comment by maliming** [comment]
You have to migrator/seed the database.

https://github.com/abpframework/eShopOnAbp#how-to-run

**Comment by gterdem** [comment]
Visual Studio debugging using the docker containers is not supported out of the box. Visual Studio IDE hooks the containers for debugging.

We suggest running them using [run-type.ps1](https://github.com/abpframework/eShopOnAbp/blob/main/run-tye.ps1). 

If you want to debug any service, comment out the related service in the [tye configuration](https://github.com/abpframework/eShopOnAbp/blob/main/tye.yaml) and debug using the IDE.
