### ISSUE TITLE
Not able to access the angular application UI 

### ISSUE THREAD

**Issue by odidev** [abpframework/eShopOnAbp#179]
Hi team, 

Continuing with our discussion in this ticket < https://github.com/abpframework/eShopOnAbp/issues/167 >, we are still facing the issue after `yarn start`. 

We can run `yarn start` successfully, but are unable to access the angular application on port 4200. Below is the output: 

![image](https://github.com/abpframework/eShopOnAbp/assets/40816837/8b2258f1-0eaa-45eb-bb1b-7a11d84df591)

 

As asked by you earlier in the ticket linked above, below are the logs for web gateway and administration services. 

1. Web Gateway: https://github.com/abpframework/eShopOnAbp/files/11734323/logs_webgateway_eshoponabp.txt
2. Administartion: https://github.com/abpframework/eShopOnAbp/files/11734326/logs_administration_service_eshoponabp.txt

Apart from these two services, I can see errors in some services, that the database “eShopOnAbp_Administration” does not exist, as below: 
~~~ 
2023-07-17 11:20:28.864 +00:00 [ERR] An error occurred using the connection to database 'EShopOnAbp_Administration' on server ''. 
2023-07-17 11:20:29.096 +00:00 [ERR] 3D000: database "EShopOnAbp_Administration" does not exist 
~~~ 
These logs can be seen in the ordering and payment services. 

Also, found the below error logs in cmskit microservice: 
~~~ 
2023-07-17 11:20:36.872 +00:00 [ERR] An exception occurred in the database while saving changes for context type 'EShopOnAbp.AdministrationService.EntityFrameworkCore.AdministrationServiceDbContext'. 
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details. 
---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "IX_AbpPermissionGroups_Name" 
~~~ 

Can you please provide some pointers on the same? Kindly let us know if you need more information from our side.

**Comment by gterdem** [comment]
Can try stopping the infrastructure and cleaning the volume of postgres db and restart the infrastructure?

**Comment by odidev** [comment]
I removed all the sqshq docker containers, and removed EShopOnAbp from the system, installed postresql and cloned EShopOnAbp, and again started the services and the angular application. But again, I am unable to access anything on the  UI at port 4200. 

However, this time I am also not seeing any error in any of the service’s logs.

**Comment by gterdem** [comment]
Can you check the browser console and network tab to see the errors?
