### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by ygr757326** [abpframework/eShopOnAbp#181]
![image](https://github.com/abpframework/eShopOnAbp/assets/42167347/71be1b44-6225-42f3-b431-56ffd4dbb2f6)
![image](https://github.com/abpframework/eShopOnAbp/assets/42167347/231b61f4-a17b-446b-bce5-0edab8e2d5f2)

**Comment by gterdem** [comment]
Try`dotnet build /graphbuild` command.
