### ISSUE TITLE
yarn start is throwing a big "failed to compile" error

### ISSUE THREAD

**Issue by justinfraz** [abpframework/eShopOnAbp#185]

**Comment by maliming** [comment]
Please share the console output.

**Comment by justinfraz** [comment]
Here it is...

[Console output.txt](https://github.com/abpframework/eShopOnAbp/files/12449368/Console.output.txt)

**Comment by justinfraz** [comment]
Hello [masumulu28](https://github.com/masumulu28)!

I am still waiting for your response to my compile error.

Best Regards,

Justin

**Comment by justinfraz** [comment]
Hello [masumulu28](https://github.com/masumulu28)!

I have an update for you.  The compile error (above) when I run start.ps1 is gone now.  As you can see in the screenshot, it is compiling successfully:

![eShopOnAbp_compilation](https://github.com/abpframework/eShopOnAbp/assets/26783435/e4ec0201-a65a-4551-a65b-544c334fecfc)

But when I open http://localhost:4200/, I am getting a new error that I wasn't gettting before:

Http failure response for http://localhost:8080/realms/master/.well-known/openid-configuration: 0 Unknown Error

Best Regards,

Justin

**Comment by masumulu28** [comment]
Hi again @justinfraz!

Thank you, I'm opening PR now, can you please open new issue with screenshots and description. I'll close this issue with PR

**Comment by justinfraz** [comment]
The eShopOnAbp angular app is compiling successfully now.

**Comment by masumulu28** [comment]
> The eShopOnAbp angular app is compiling successfully now.

Let PR close issue please 🙂

**Comment by justinfraz** [comment]
What do you mean by "Let PR close issue please"?  Do you mean that we should let PR close this issue and not us?  What does "PR" stand for?

**Comment by masumulu28** [comment]
Yes, for review on my teammate
