### ISSUE TITLE
SocketException on running run-tye.ps1

### ISSUE THREAD

**Issue by JunqiaoDuan** [abpframework/eShopOnAbp#187]
When I run run-tye.ps1 to run the services, I got a exceptions:
![image](https://github.com/abpframework/eShopOnAbp/assets/6871657/d9975136-d394-44d2-9ff6-e14356cd8d88)
Is it the reason that Port was Occupied?
How can I find which port is occupied?

**Comment by gterdem** [comment]
Here is the list of used ports:

**Applications:**
- Angular: http://localhost:4200
- PublicWeb: https://localhost:44335
- KeycloakServer: https://localhost:8080

**Gateways:**
- WebGateway: https://localhost:44372
- PublicWebGateway: https://localhost:44373

**Microservices:**
- IdentityService: https://localhost:44351
- AdministrationService: https://localhost:44353
- CatalogService: https://localhost:44354
- BasketService: https://localhost:44355
- OrderingService: https://localhost:44356
- PaymentService: https://localhost:44357
- CmsKitService: https://localhost:44358

**Infrastructure:**
- RabbitMq: https://localhost:15672
- MongoExpress: https://localhost:8081
- PgAdmin: https://localhost:5050

**Comment by gterdem** [comment]
Closing the issue. Feel free to re-open if the problem still persist.
