### ISSUE TITLE
Add demo website GitHub link to the footer

### ISSUE THREAD

**Issue by ebicoglu** [abpframework/eShopOnAbp#211]
Add the following information to the footer of the demo website:

> This website is built on top of the [ABP Framework](https://abp.io/) and the source-code is available at [github.com/abpframework/eshoponabp](https://github.com/abpframework/eShopOnAbp)

![image](https://github.com/abpframework/eShopOnAbp/assets/9526587/fe453782-cc3c-4687-ba7e-59a0addbe6ed)

---

Secondly, add a padding to the right side of the login link:

![image](https://github.com/abpframework/eShopOnAbp/assets/9526587/d10738bb-66b3-479a-b6c6-bc94999bb8af)

**Comment by skoc10** [comment]
The latest version 1.1.0 was deployed
The error here looks like a database connection error.
<img width="1380" alt="image" src="https://github.com/abpframework/eShopOnAbp/assets/64414348/1ef38bd4-f502-4bd8-8ec6-c9c10c27db8c">
