### ISSUE TITLE
Update Permission User but do not render Sidemenu.

### ISSUE THREAD

**Issue by StevenNgoc** [abpframework/eShopOnAbp#234]
I run Example eShopOnAbp in local evironment.
My problem, when update permission with permission-managent module in Administration Service.

1. Update in identity/roles -> Sidemenu auto render (ThemeLeptonX)
2. But update in identity/users nothing happens

I check code step by step and detection permission dont update in caching ( I use redis). Both UI call api is the same (/api/permission-management/permissions - Put method).
Please help me how fix my problem. Thanks all

**Comment by gterdem** [comment]
Nice to hear your problem is being solved.
Closing the issue.
